name: build

on:
  pull_request:
    branches:
    - "*"
  push:
    branches:
    - main
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    permissions:
      checks: write
      contents: write
      packages: write
      statuses: write
      attestations: write
      id-token: write
    env:
      IMAGE: ghcr.io/davidkarlsen/utils-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.IMAGE }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          #platforms: linux/amd64,linux/arm64
          platform: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Attest
        uses: actions/attest@v1
        id: attest
        with:
          subject-name: ${{ env.IMAGE }}
          subject-digest: ${{ steps.build-push.outputs.digest }}
          push-to-registry: true
          predicate-type: 'https://in-toto.io/attestation/release/v0.1'
          predicate: '{"purl":"pkg:oci/..."}'
